// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: protofile/actormsg.proto

package protofile

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MSG_TYPE int32

const (
	//------------------ actor proto 服务器内部通信使用 id段 1-1000 --------------------------------------
	MSG_TYPE_ACTOR_MSG           MSG_TYPE = 0 //
	MSG_TYPE_ACTOR_HEATBEAT_PING MSG_TYPE = 1 // 心跳 主动连接的一方发送
	MSG_TYPE_ACTOR_HEATBEAT_PONG MSG_TYPE = 2 // 心跳 被动连接回复
	MSG_TYPE_ACTOR_REGIST        MSG_TYPE = 3 // 注册
	MSG_TYPE_ACTOR_MESSAGE       MSG_TYPE = 4 // 传输数据
	MSG_TYPE_ACTOR_DETECT        MSG_TYPE = 5 // 探测信号
	MSG_TYPE_ACTOR_DETECT_RESP   MSG_TYPE = 6 // 探测信号返回
)

// Enum value maps for MSG_TYPE.
var (
	MSG_TYPE_name = map[int32]string{
		0: "ACTOR_MSG",
		1: "ACTOR_HEATBEAT_PING",
		2: "ACTOR_HEATBEAT_PONG",
		3: "ACTOR_REGIST",
		4: "ACTOR_MESSAGE",
		5: "ACTOR_DETECT",
		6: "ACTOR_DETECT_RESP",
	}
	MSG_TYPE_value = map[string]int32{
		"ACTOR_MSG":           0,
		"ACTOR_HEATBEAT_PING": 1,
		"ACTOR_HEATBEAT_PONG": 2,
		"ACTOR_REGIST":        3,
		"ACTOR_MESSAGE":       4,
		"ACTOR_DETECT":        5,
		"ACTOR_DETECT_RESP":   6,
	}
)

func (x MSG_TYPE) Enum() *MSG_TYPE {
	p := new(MSG_TYPE)
	*p = x
	return p
}

func (x MSG_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MSG_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_protofile_actormsg_proto_enumTypes[0].Descriptor()
}

func (MSG_TYPE) Type() protoreflect.EnumType {
	return &file_protofile_actormsg_proto_enumTypes[0]
}

func (x MSG_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MSG_TYPE.Descriptor instead.
func (MSG_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_protofile_actormsg_proto_rawDescGZIP(), []int{0}
}

type ActorMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ActorMsg) Reset() {
	*x = ActorMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_actormsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorMsg) ProtoMessage() {}

func (x *ActorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_actormsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorMsg.ProtoReflect.Descriptor instead.
func (*ActorMsg) Descriptor() ([]byte, []int) {
	return file_protofile_actormsg_proto_rawDescGZIP(), []int{0}
}

type ActorHeatbeatPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr"`
}

func (x *ActorHeatbeatPing) Reset() {
	*x = ActorHeatbeatPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_actormsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorHeatbeatPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorHeatbeatPing) ProtoMessage() {}

func (x *ActorHeatbeatPing) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_actormsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorHeatbeatPing.ProtoReflect.Descriptor instead.
func (*ActorHeatbeatPing) Descriptor() ([]byte, []int) {
	return file_protofile_actormsg_proto_rawDescGZIP(), []int{1}
}

func (x *ActorHeatbeatPing) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ActorHeatbeatPong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=Addr,proto3" json:"Addr"`
}

func (x *ActorHeatbeatPong) Reset() {
	*x = ActorHeatbeatPong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_actormsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorHeatbeatPong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorHeatbeatPong) ProtoMessage() {}

func (x *ActorHeatbeatPong) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_actormsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorHeatbeatPong.ProtoReflect.Descriptor instead.
func (*ActorHeatbeatPong) Descriptor() ([]byte, []int) {
	return file_protofile_actormsg_proto_rawDescGZIP(), []int{2}
}

func (x *ActorHeatbeatPong) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type ActorRegist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorId []string `protobuf:"bytes,1,rep,name=actorId,proto3" json:"actorId"`
}

func (x *ActorRegist) Reset() {
	*x = ActorRegist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_actormsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorRegist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorRegist) ProtoMessage() {}

func (x *ActorRegist) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_actormsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorRegist.ProtoReflect.Descriptor instead.
func (*ActorRegist) Descriptor() ([]byte, []int) {
	return file_protofile_actormsg_proto_rawDescGZIP(), []int{3}
}

func (x *ActorRegist) GetActorId() []string {
	if x != nil {
		return x.ActorId
	}
	return nil
}

type ActorMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateSession string `protobuf:"bytes,1,opt,name=GateSession,proto3" json:"GateSession"` // gate1:50400001
	SourceId    string `protobuf:"bytes,2,opt,name=SourceId,proto3" json:"SourceId"`
	TargetId    string `protobuf:"bytes,3,opt,name=TargetId,proto3" json:"TargetId"`
	MsgId       int32  `protobuf:"varint,4,opt,name=MsgId,proto3" json:"MsgId"`
	Data        []byte `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data"`
}

func (x *ActorMessage) Reset() {
	*x = ActorMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_actormsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorMessage) ProtoMessage() {}

func (x *ActorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_actormsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorMessage.ProtoReflect.Descriptor instead.
func (*ActorMessage) Descriptor() ([]byte, []int) {
	return file_protofile_actormsg_proto_rawDescGZIP(), []int{4}
}

func (x *ActorMessage) GetGateSession() string {
	if x != nil {
		return x.GateSession
	}
	return ""
}

func (x *ActorMessage) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ActorMessage) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ActorMessage) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ActorMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ActorDetect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ActorDetect) Reset() {
	*x = ActorDetect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_actormsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorDetect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorDetect) ProtoMessage() {}

func (x *ActorDetect) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_actormsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorDetect.ProtoReflect.Descriptor instead.
func (*ActorDetect) Descriptor() ([]byte, []int) {
	return file_protofile_actormsg_proto_rawDescGZIP(), []int{5}
}

type ActorDetectResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ActorDetectResp) Reset() {
	*x = ActorDetectResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_actormsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActorDetectResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorDetectResp) ProtoMessage() {}

func (x *ActorDetectResp) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_actormsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorDetectResp.ProtoReflect.Descriptor instead.
func (*ActorDetectResp) Descriptor() ([]byte, []int) {
	return file_protofile_actormsg_proto_rawDescGZIP(), []int{6}
}

var File_protofile_actormsg_proto protoreflect.FileDescriptor

var file_protofile_actormsg_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x0a, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x4d, 0x73,
	0x67, 0x22, 0x27, 0x0a, 0x11, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x48, 0x65, 0x61, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x22, 0x27, 0x0a, 0x11, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x48, 0x65, 0x61, 0x74, 0x62, 0x65, 0x61, 0x74, 0x50, 0x6f, 0x6e, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41,
	0x64, 0x64, 0x72, 0x22, 0x27, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x92, 0x01, 0x0a,
	0x0c, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x0d, 0x0a, 0x0b, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x22, 0x11, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x2a, 0x99, 0x01, 0x0a, 0x08, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x12, 0x0d, 0x0a, 0x09, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x4d, 0x53, 0x47, 0x10, 0x00, 0x12,
	0x17, 0x0a, 0x13, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x48, 0x45, 0x41, 0x54, 0x42, 0x45, 0x41,
	0x54, 0x5f, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x54, 0x4f,
	0x52, 0x5f, 0x48, 0x45, 0x41, 0x54, 0x42, 0x45, 0x41, 0x54, 0x5f, 0x50, 0x4f, 0x4e, 0x47, 0x10,
	0x02, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53,
	0x54, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x4d, 0x45, 0x53,
	0x53, 0x41, 0x47, 0x45, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x5f,
	0x44, 0x45, 0x54, 0x45, 0x43, 0x54, 0x10, 0x05, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x43, 0x54, 0x4f,
	0x52, 0x5f, 0x44, 0x45, 0x54, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x06, 0x42,
	0x0c, 0x5a, 0x0a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofile_actormsg_proto_rawDescOnce sync.Once
	file_protofile_actormsg_proto_rawDescData = file_protofile_actormsg_proto_rawDesc
)

func file_protofile_actormsg_proto_rawDescGZIP() []byte {
	file_protofile_actormsg_proto_rawDescOnce.Do(func() {
		file_protofile_actormsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofile_actormsg_proto_rawDescData)
	})
	return file_protofile_actormsg_proto_rawDescData
}

var file_protofile_actormsg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protofile_actormsg_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protofile_actormsg_proto_goTypes = []interface{}{
	(MSG_TYPE)(0),             // 0: protofile.MSG_TYPE
	(*ActorMsg)(nil),          // 1: protofile.ActorMsg
	(*ActorHeatbeatPing)(nil), // 2: protofile.ActorHeatbeatPing
	(*ActorHeatbeatPong)(nil), // 3: protofile.ActorHeatbeatPong
	(*ActorRegist)(nil),       // 4: protofile.ActorRegist
	(*ActorMessage)(nil),      // 5: protofile.ActorMessage
	(*ActorDetect)(nil),       // 6: protofile.ActorDetect
	(*ActorDetectResp)(nil),   // 7: protofile.ActorDetectResp
}
var file_protofile_actormsg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protofile_actormsg_proto_init() }
func file_protofile_actormsg_proto_init() {
	if File_protofile_actormsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofile_actormsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_actormsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorHeatbeatPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_actormsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorHeatbeatPong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_actormsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorRegist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_actormsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_actormsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorDetect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_actormsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActorDetectResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofile_actormsg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protofile_actormsg_proto_goTypes,
		DependencyIndexes: file_protofile_actormsg_proto_depIdxs,
		EnumInfos:         file_protofile_actormsg_proto_enumTypes,
		MessageInfos:      file_protofile_actormsg_proto_msgTypes,
	}.Build()
	File_protofile_actormsg_proto = out.File
	file_protofile_actormsg_proto_rawDesc = nil
	file_protofile_actormsg_proto_goTypes = nil
	file_protofile_actormsg_proto_depIdxs = nil
}
