package config_go

// Code generated by excelExoprt. DO NOT EDIT.
// source: CherrySlot.xlsx

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"path"
)

// array and map
var _CherryBonusCombineMap = map[string]*CherryBonusCombine{}
var _CherryBonusCombineArray = []*CherryBonusCombine{}

type CherryBonusCombine struct {
	data *_CherryBonusCombine
}

// 类型结构
type _CherryBonusCombine struct {
	STR_ID           string    // 原始位置
	ARRAYSTR_Combine array_str // 合并位置
}

func (c *CherryBonusCombine) ID() string { return c.data.STR_ID } //原始位置
//合并位置
func (c *CherryBonusCombine) Len_Combine() int           { return c.data.ARRAYSTR_Combine.Len() }
func (c *CherryBonusCombine) Get_Combine(key int) string { return c.data.ARRAYSTR_Combine.Get(key) }
func (c *CherryBonusCombine) Range_Combine(fn func(int, string) (stop bool)) {
	c.data.ARRAYSTR_Combine.Range(fn)
}
func (c *CherryBonusCombine) Copy_Combine() array_str { return c.data.ARRAYSTR_Combine.Copy() }

func HasCherryBonusCombine(key string) bool {
	_, ok := _CherryBonusCombineMap[key]
	return ok
}

func GetCherryBonusCombine(key string) *CherryBonusCombine {
	return _CherryBonusCombineMap[key]
}

func RangeCherryBonusCombine(fn func(i int, row *CherryBonusCombine) (stop bool)) {
	for i, row := range _CherryBonusCombineArray {
		if fn(i, row) {
			break
		}
	}
}

func LenCherryBonusCombine() int { return len(_CherryBonusCombineArray) }

func init() {
	loadfn["CherryBonusCombine"] = loadCherryBonusCombine
}

func loadCherryBonusCombine(dir string) error {
	data, err := ioutil.ReadFile(path.Join(dir, "CherryBonusCombine.json"))
	if err != nil {
		return fmt.Errorf("file=%v read err=%v", err.Error())
	}

	datas := []*_CherryBonusCombine{}
	err = json.Unmarshal(data, &datas)
	if err != nil {
		return fmt.Errorf("file=%v parse err=%v", err.Error())
	}

	result_array := []*CherryBonusCombine{}
	result_map := map[string]*CherryBonusCombine{}
	for _, row := range datas {
		data := &CherryBonusCombine{data: row}
		result_array = append(result_array, data)
		result_map[row.STR_ID] = data
	}
	_CherryBonusCombineArray = result_array
	_CherryBonusCombineMap = result_map
	fmt.Printf("%-50v len:%v\n", "CherryBonusCombine load finish! ", len(result_array))
	return nil
}
