// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        (unknown)
// source: dice.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 同步骰子游戏信息
type NotifyDiceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsonInfo string `protobuf:"bytes,1,opt,name=JsonInfo,json=jsonInfo,proto3" json:"JsonInfo"`
}

func (x *NotifyDiceInfo) Reset() {
	*x = NotifyDiceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyDiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyDiceInfo) ProtoMessage() {}

func (x *NotifyDiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyDiceInfo.ProtoReflect.Descriptor instead.
func (*NotifyDiceInfo) Descriptor() ([]byte, []int) {
	return file_dice_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyDiceInfo) GetJsonInfo() string {
	if x != nil {
		return x.JsonInfo
	}
	return ""
}

// 保存游戏信息
type DiceSaveInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsonInfo     string          `protobuf:"bytes,1,opt,name=JsonInfo,json=jsonInfo,proto3" json:"JsonInfo"`
	ConsumeItems map[int32]int64 `protobuf:"bytes,2,rep,name=ConsumeItems,json=consumeItems,proto3" json:"ConsumeItems" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 消耗道具
	AcquireItems map[int32]int64 `protobuf:"bytes,3,rep,name=AcquireItems,json=acquireItems,proto3" json:"AcquireItems" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` // 获得道具
}

func (x *DiceSaveInfoReq) Reset() {
	*x = DiceSaveInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiceSaveInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiceSaveInfoReq) ProtoMessage() {}

func (x *DiceSaveInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_dice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiceSaveInfoReq.ProtoReflect.Descriptor instead.
func (*DiceSaveInfoReq) Descriptor() ([]byte, []int) {
	return file_dice_proto_rawDescGZIP(), []int{1}
}

func (x *DiceSaveInfoReq) GetJsonInfo() string {
	if x != nil {
		return x.JsonInfo
	}
	return ""
}

func (x *DiceSaveInfoReq) GetConsumeItems() map[int32]int64 {
	if x != nil {
		return x.ConsumeItems
	}
	return nil
}

func (x *DiceSaveInfoReq) GetAcquireItems() map[int32]int64 {
	if x != nil {
		return x.AcquireItems
	}
	return nil
}

type DiceSaveInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result MSG_RESULT `protobuf:"varint,1,opt,name=Result,json=result,proto3,enum=message.MSG_RESULT" json:"Result"` //成功码
}

func (x *DiceSaveInfoRes) Reset() {
	*x = DiceSaveInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiceSaveInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiceSaveInfoRes) ProtoMessage() {}

func (x *DiceSaveInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_dice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiceSaveInfoRes.ProtoReflect.Descriptor instead.
func (*DiceSaveInfoRes) Descriptor() ([]byte, []int) {
	return file_dice_proto_rawDescGZIP(), []int{2}
}

func (x *DiceSaveInfoRes) GetResult() MSG_RESULT {
	if x != nil {
		return x.Result
	}
	return MSG_RESULT_SUCCESS
}

var File_dice_proto protoreflect.FileDescriptor

var file_dice_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0d, 0x6d, 0x73, 0x67, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x0e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x69,
	0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x4a, 0x73, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0xcf, 0x02, 0x0a, 0x0f, 0x44, 0x69, 0x63, 0x65, 0x53, 0x61, 0x76, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x4a, 0x73, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x4e, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x44, 0x69, 0x63, 0x65, 0x53, 0x61, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x4e, 0x0a, 0x0c, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x44, 0x69, 0x63, 0x65, 0x53, 0x61, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x2e, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x61, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x1a, 0x3f, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x3f, 0x0a, 0x11, 0x41, 0x63, 0x71, 0x75, 0x69, 0x72, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x3e, 0x0a, 0x0f, 0x44, 0x69, 0x63, 0x65, 0x53, 0x61, 0x76, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dice_proto_rawDescOnce sync.Once
	file_dice_proto_rawDescData = file_dice_proto_rawDesc
)

func file_dice_proto_rawDescGZIP() []byte {
	file_dice_proto_rawDescOnce.Do(func() {
		file_dice_proto_rawDescData = protoimpl.X.CompressGZIP(file_dice_proto_rawDescData)
	})
	return file_dice_proto_rawDescData
}

var file_dice_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dice_proto_goTypes = []interface{}{
	(*NotifyDiceInfo)(nil),  // 0: message.NotifyDiceInfo
	(*DiceSaveInfoReq)(nil), // 1: message.DiceSaveInfoReq
	(*DiceSaveInfoRes)(nil), // 2: message.DiceSaveInfoRes
	nil,                     // 3: message.DiceSaveInfoReq.ConsumeItemsEntry
	nil,                     // 4: message.DiceSaveInfoReq.AcquireItemsEntry
	(MSG_RESULT)(0),         // 5: message.MSG_RESULT
}
var file_dice_proto_depIdxs = []int32{
	3, // 0: message.DiceSaveInfoReq.ConsumeItems:type_name -> message.DiceSaveInfoReq.ConsumeItemsEntry
	4, // 1: message.DiceSaveInfoReq.AcquireItems:type_name -> message.DiceSaveInfoReq.AcquireItemsEntry
	5, // 2: message.DiceSaveInfoRes.Result:type_name -> message.MSG_RESULT
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dice_proto_init() }
func file_dice_proto_init() {
	if File_dice_proto != nil {
		return
	}
	file_msgtype_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyDiceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiceSaveInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiceSaveInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dice_proto_goTypes,
		DependencyIndexes: file_dice_proto_depIdxs,
		MessageInfos:      file_dice_proto_msgTypes,
	}.Build()
	File_dice_proto = out.File
	file_dice_proto_rawDesc = nil
	file_dice_proto_goTypes = nil
	file_dice_proto_depIdxs = nil
}
