// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        (unknown)
// source: msgbuilding.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 同步建筑信息
type NotifyBuildingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//[Sync(Root.Role.Buildings, Update, v => v.Id)]
	Buildings []*Building `protobuf:"bytes,1,rep,name=Buildings,json=buildings,proto3" json:"Buildings"`
}

func (x *NotifyBuildingInfo) Reset() {
	*x = NotifyBuildingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgbuilding_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyBuildingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBuildingInfo) ProtoMessage() {}

func (x *NotifyBuildingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msgbuilding_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBuildingInfo.ProtoReflect.Descriptor instead.
func (*NotifyBuildingInfo) Descriptor() ([]byte, []int) {
	return file_msgbuilding_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyBuildingInfo) GetBuildings() []*Building {
	if x != nil {
		return x.Buildings
	}
	return nil
}

//  建筑升级请求
type BuildingLevelUpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32 `protobuf:"varint,1,opt,name=Id,json=id,proto3" json:"Id"`                      //建筑Id
	UptoLevel int32 `protobuf:"varint,2,opt,name=UptoLevel,json=uptoLevel,proto3" json:"UptoLevel"` //提升到多少级
}

func (x *BuildingLevelUpReq) Reset() {
	*x = BuildingLevelUpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgbuilding_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildingLevelUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingLevelUpReq) ProtoMessage() {}

func (x *BuildingLevelUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_msgbuilding_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingLevelUpReq.ProtoReflect.Descriptor instead.
func (*BuildingLevelUpReq) Descriptor() ([]byte, []int) {
	return file_msgbuilding_proto_rawDescGZIP(), []int{1}
}

func (x *BuildingLevelUpReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuildingLevelUpReq) GetUptoLevel() int32 {
	if x != nil {
		return x.UptoLevel
	}
	return 0
}

//  建筑升级回复
type BuildingLevelUpRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result MSG_RESULT `protobuf:"varint,1,opt,name=Result,json=result,proto3,enum=message.MSG_RESULT" json:"Result"` //成功码
}

func (x *BuildingLevelUpRes) Reset() {
	*x = BuildingLevelUpRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgbuilding_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildingLevelUpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingLevelUpRes) ProtoMessage() {}

func (x *BuildingLevelUpRes) ProtoReflect() protoreflect.Message {
	mi := &file_msgbuilding_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingLevelUpRes.ProtoReflect.Descriptor instead.
func (*BuildingLevelUpRes) Descriptor() ([]byte, []int) {
	return file_msgbuilding_proto_rawDescGZIP(), []int{2}
}

func (x *BuildingLevelUpRes) GetResult() MSG_RESULT {
	if x != nil {
		return x.Result
	}
	return MSG_RESULT_SUCCESS
}

//  建筑升星
type BuildingStarUpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32 `protobuf:"varint,1,opt,name=Id,json=id,proto3" json:"Id"`
	UptoStar int32 `protobuf:"varint,2,opt,name=UptoStar,json=uptoStar,proto3" json:"UptoStar"` //提升到多少星
}

func (x *BuildingStarUpReq) Reset() {
	*x = BuildingStarUpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgbuilding_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildingStarUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingStarUpReq) ProtoMessage() {}

func (x *BuildingStarUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_msgbuilding_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingStarUpReq.ProtoReflect.Descriptor instead.
func (*BuildingStarUpReq) Descriptor() ([]byte, []int) {
	return file_msgbuilding_proto_rawDescGZIP(), []int{3}
}

func (x *BuildingStarUpReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BuildingStarUpReq) GetUptoStar() int32 {
	if x != nil {
		return x.UptoStar
	}
	return 0
}

//  建筑升星回复
type BuildingStarUpRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result MSG_RESULT `protobuf:"varint,1,opt,name=Result,json=result,proto3,enum=message.MSG_RESULT" json:"Result"` //成功码
}

func (x *BuildingStarUpRes) Reset() {
	*x = BuildingStarUpRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgbuilding_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildingStarUpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingStarUpRes) ProtoMessage() {}

func (x *BuildingStarUpRes) ProtoReflect() protoreflect.Message {
	mi := &file_msgbuilding_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingStarUpRes.ProtoReflect.Descriptor instead.
func (*BuildingStarUpRes) Descriptor() ([]byte, []int) {
	return file_msgbuilding_proto_rawDescGZIP(), []int{4}
}

func (x *BuildingStarUpRes) GetResult() MSG_RESULT {
	if x != nil {
		return x.Result
	}
	return MSG_RESULT_SUCCESS
}

//  建筑属性升级
type BuildingPropUpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildingId int32 `protobuf:"varint,1,opt,name=BuildingId,json=buildingId,proto3" json:"BuildingId"`
	PropId     int32 `protobuf:"varint,2,opt,name=PropId,json=propId,proto3" json:"PropId"`
	UptoLevel  int32 `protobuf:"varint,3,opt,name=UptoLevel,json=uptoLevel,proto3" json:"UptoLevel"` //提升到多少级
}

func (x *BuildingPropUpReq) Reset() {
	*x = BuildingPropUpReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgbuilding_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildingPropUpReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingPropUpReq) ProtoMessage() {}

func (x *BuildingPropUpReq) ProtoReflect() protoreflect.Message {
	mi := &file_msgbuilding_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingPropUpReq.ProtoReflect.Descriptor instead.
func (*BuildingPropUpReq) Descriptor() ([]byte, []int) {
	return file_msgbuilding_proto_rawDescGZIP(), []int{5}
}

func (x *BuildingPropUpReq) GetBuildingId() int32 {
	if x != nil {
		return x.BuildingId
	}
	return 0
}

func (x *BuildingPropUpReq) GetPropId() int32 {
	if x != nil {
		return x.PropId
	}
	return 0
}

func (x *BuildingPropUpReq) GetUptoLevel() int32 {
	if x != nil {
		return x.UptoLevel
	}
	return 0
}

//  建筑属性升级回复
type BuildingPropUpRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result MSG_RESULT `protobuf:"varint,1,opt,name=Result,json=result,proto3,enum=message.MSG_RESULT" json:"Result"` //成功码
}

func (x *BuildingPropUpRes) Reset() {
	*x = BuildingPropUpRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgbuilding_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildingPropUpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingPropUpRes) ProtoMessage() {}

func (x *BuildingPropUpRes) ProtoReflect() protoreflect.Message {
	mi := &file_msgbuilding_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingPropUpRes.ProtoReflect.Descriptor instead.
func (*BuildingPropUpRes) Descriptor() ([]byte, []int) {
	return file_msgbuilding_proto_rawDescGZIP(), []int{6}
}

func (x *BuildingPropUpRes) GetResult() MSG_RESULT {
	if x != nil {
		return x.Result
	}
	return MSG_RESULT_SUCCESS
}

var File_msgbuilding_proto protoreflect.FileDescriptor

var file_msgbuilding_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x73, 0x67, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0a, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6d, 0x73, 0x67, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a,
	0x09, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x42,
	0x0a, 0x12, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x55,
	0x70, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x74, 0x6f, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x75, 0x70, 0x74, 0x6f, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x22, 0x41, 0x0a, 0x12, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x55, 0x70, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x3f, 0x0a, 0x11, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e,
	0x67, 0x53, 0x74, 0x61, 0x72, 0x55, 0x70, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x70,
	0x74, 0x6f, 0x53, 0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x75, 0x70,
	0x74, 0x6f, 0x53, 0x74, 0x61, 0x72, 0x22, 0x40, 0x0a, 0x11, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69,
	0x6e, 0x67, 0x53, 0x74, 0x61, 0x72, 0x55, 0x70, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x69, 0x0a, 0x11, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x70, 0x55, 0x70, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a,
	0x0a, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70,
	0x72, 0x6f, 0x70, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x74, 0x6f, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x75, 0x70, 0x74, 0x6f, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x22, 0x40, 0x0a, 0x11, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x50,
	0x72, 0x6f, 0x70, 0x55, 0x70, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgbuilding_proto_rawDescOnce sync.Once
	file_msgbuilding_proto_rawDescData = file_msgbuilding_proto_rawDesc
)

func file_msgbuilding_proto_rawDescGZIP() []byte {
	file_msgbuilding_proto_rawDescOnce.Do(func() {
		file_msgbuilding_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgbuilding_proto_rawDescData)
	})
	return file_msgbuilding_proto_rawDescData
}

var file_msgbuilding_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_msgbuilding_proto_goTypes = []interface{}{
	(*NotifyBuildingInfo)(nil), // 0: message.NotifyBuildingInfo
	(*BuildingLevelUpReq)(nil), // 1: message.BuildingLevelUpReq
	(*BuildingLevelUpRes)(nil), // 2: message.BuildingLevelUpRes
	(*BuildingStarUpReq)(nil),  // 3: message.BuildingStarUpReq
	(*BuildingStarUpRes)(nil),  // 4: message.BuildingStarUpRes
	(*BuildingPropUpReq)(nil),  // 5: message.BuildingPropUpReq
	(*BuildingPropUpRes)(nil),  // 6: message.BuildingPropUpRes
	(*Building)(nil),           // 7: message.Building
	(MSG_RESULT)(0),            // 8: message.MSG_RESULT
}
var file_msgbuilding_proto_depIdxs = []int32{
	7, // 0: message.NotifyBuildingInfo.Buildings:type_name -> message.Building
	8, // 1: message.BuildingLevelUpRes.Result:type_name -> message.MSG_RESULT
	8, // 2: message.BuildingStarUpRes.Result:type_name -> message.MSG_RESULT
	8, // 3: message.BuildingPropUpRes.Result:type_name -> message.MSG_RESULT
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_msgbuilding_proto_init() }
func file_msgbuilding_proto_init() {
	if File_msgbuilding_proto != nil {
		return
	}
	file_base_proto_init()
	file_msgtype_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msgbuilding_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyBuildingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgbuilding_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildingLevelUpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgbuilding_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildingLevelUpRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgbuilding_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildingStarUpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgbuilding_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildingStarUpRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgbuilding_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildingPropUpReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgbuilding_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildingPropUpRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgbuilding_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgbuilding_proto_goTypes,
		DependencyIndexes: file_msgbuilding_proto_depIdxs,
		MessageInfos:      file_msgbuilding_proto_msgTypes,
	}.Build()
	File_msgbuilding_proto = out.File
	file_msgbuilding_proto_rawDesc = nil
	file_msgbuilding_proto_goTypes = nil
	file_msgbuilding_proto_depIdxs = nil
}
