// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        (unknown)
// source: msgItem.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TIP_TYPE int32

const (
	TIP_TYPE_NORMAL TIP_TYPE = 0
)

// Enum value maps for TIP_TYPE.
var (
	TIP_TYPE_name = map[int32]string{
		0: "NORMAL",
	}
	TIP_TYPE_value = map[string]int32{
		"NORMAL": 0,
	}
)

func (x TIP_TYPE) Enum() *TIP_TYPE {
	p := new(TIP_TYPE)
	*p = x
	return p
}

func (x TIP_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TIP_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_msgItem_proto_enumTypes[0].Descriptor()
}

func (TIP_TYPE) Type() protoreflect.EnumType {
	return &file_msgItem_proto_enumTypes[0]
}

func (x TIP_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TIP_TYPE.Descriptor instead.
func (TIP_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_msgItem_proto_rawDescGZIP(), []int{0}
}

// 同步背包道具
type NotifyItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//[Sync(Root.Role.Items, Update, v => v.Id)]
	Items []*Item `protobuf:"bytes,1,rep,name=Items,json=items,proto3" json:"Items"`
}

func (x *NotifyItems) Reset() {
	*x = NotifyItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgItem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyItems) ProtoMessage() {}

func (x *NotifyItems) ProtoReflect() protoreflect.Message {
	mi := &file_msgItem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyItems.ProtoReflect.Descriptor instead.
func (*NotifyItems) Descriptor() ([]byte, []int) {
	return file_msgItem_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyItems) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

//使用道具
type UseItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int32         `protobuf:"varint,1,opt,name=ItemId,json=itemId,proto3" json:"ItemId"`
	Count  int64         `protobuf:"varint,2,opt,name=Count,json=count,proto3" json:"Count"`
	Params *UseExtParams `protobuf:"bytes,3,opt,name=Params,json=params,proto3" json:"Params"`
}

func (x *UseItemReq) Reset() {
	*x = UseItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgItem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemReq) ProtoMessage() {}

func (x *UseItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_msgItem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemReq.ProtoReflect.Descriptor instead.
func (*UseItemReq) Descriptor() ([]byte, []int) {
	return file_msgItem_proto_rawDescGZIP(), []int{1}
}

func (x *UseItemReq) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *UseItemReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UseItemReq) GetParams() *UseExtParams {
	if x != nil {
		return x.Params
	}
	return nil
}

//使用道具回复
type UseItemRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result MSG_RESULT `protobuf:"varint,1,opt,name=Result,json=result,proto3,enum=message.MSG_RESULT" json:"Result"` //成功码
}

func (x *UseItemRes) Reset() {
	*x = UseItemRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgItem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseItemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemRes) ProtoMessage() {}

func (x *UseItemRes) ProtoReflect() protoreflect.Message {
	mi := &file_msgItem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemRes.ProtoReflect.Descriptor instead.
func (*UseItemRes) Descriptor() ([]byte, []int) {
	return file_msgItem_proto_rawDescGZIP(), []int{2}
}

func (x *UseItemRes) GetResult() MSG_RESULT {
	if x != nil {
		return x.Result
	}
	return MSG_RESULT_SUCCESS
}

type UseExtParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UseExtParams) Reset() {
	*x = UseExtParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgItem_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseExtParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseExtParams) ProtoMessage() {}

func (x *UseExtParams) ProtoReflect() protoreflect.Message {
	mi := &file_msgItem_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseExtParams.ProtoReflect.Descriptor instead.
func (*UseExtParams) Descriptor() ([]byte, []int) {
	return file_msgItem_proto_rawDescGZIP(), []int{3}
}

// 道具获得弹窗
type NotifyTipItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tip   TIP_TYPE `protobuf:"varint,1,opt,name=Tip,json=tip,proto3,enum=message.TIP_TYPE" json:"Tip"`
	Items []*Item  `protobuf:"bytes,2,rep,name=Items,json=items,proto3" json:"Items"` //仅显示使用的道具列表 不需要同步到角色数据
}

func (x *NotifyTipItems) Reset() {
	*x = NotifyTipItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgItem_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyTipItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTipItems) ProtoMessage() {}

func (x *NotifyTipItems) ProtoReflect() protoreflect.Message {
	mi := &file_msgItem_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTipItems.ProtoReflect.Descriptor instead.
func (*NotifyTipItems) Descriptor() ([]byte, []int) {
	return file_msgItem_proto_rawDescGZIP(), []int{4}
}

func (x *NotifyTipItems) GetTip() TIP_TYPE {
	if x != nil {
		return x.Tip
	}
	return TIP_TYPE_NORMAL
}

func (x *NotifyTipItems) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 出售道具
type SellItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=Items,json=items,proto3" json:"Items"`
}

func (x *SellItemReq) Reset() {
	*x = SellItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgItem_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellItemReq) ProtoMessage() {}

func (x *SellItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_msgItem_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellItemReq.ProtoReflect.Descriptor instead.
func (*SellItemReq) Descriptor() ([]byte, []int) {
	return file_msgItem_proto_rawDescGZIP(), []int{5}
}

func (x *SellItemReq) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 出售道具
type SellItemRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result MSG_RESULT `protobuf:"varint,1,opt,name=Result,json=result,proto3,enum=message.MSG_RESULT" json:"Result"` //成功码
}

func (x *SellItemRes) Reset() {
	*x = SellItemRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgItem_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SellItemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellItemRes) ProtoMessage() {}

func (x *SellItemRes) ProtoReflect() protoreflect.Message {
	mi := &file_msgItem_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellItemRes.ProtoReflect.Descriptor instead.
func (*SellItemRes) Descriptor() ([]byte, []int) {
	return file_msgItem_proto_rawDescGZIP(), []int{6}
}

func (x *SellItemRes) GetResult() MSG_RESULT {
	if x != nil {
		return x.Result
	}
	return MSG_RESULT_SUCCESS
}

var File_msgItem_proto protoreflect.FileDescriptor

var file_msgItem_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x73, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6d, 0x73, 0x67, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x69, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x55, 0x73,
	0x65, 0x45, 0x78, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x22, 0x39, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73,
	0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x53, 0x47, 0x5f, 0x52,
	0x45, 0x53, 0x55, 0x4c, 0x54, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x0e, 0x0a,
	0x0c, 0x55, 0x73, 0x65, 0x45, 0x78, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x5a, 0x0a,
	0x0e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x69, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12,
	0x23, 0x0a, 0x03, 0x54, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x54, 0x49, 0x50, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52,
	0x03, 0x74, 0x69, 0x70, 0x12, 0x23, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x32, 0x0a, 0x0b, 0x53, 0x65, 0x6c,
	0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x3a, 0x0a,
	0x0b, 0x53, 0x65, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c,
	0x54, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x16, 0x0a, 0x08, 0x54, 0x49, 0x50,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10,
	0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgItem_proto_rawDescOnce sync.Once
	file_msgItem_proto_rawDescData = file_msgItem_proto_rawDesc
)

func file_msgItem_proto_rawDescGZIP() []byte {
	file_msgItem_proto_rawDescOnce.Do(func() {
		file_msgItem_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgItem_proto_rawDescData)
	})
	return file_msgItem_proto_rawDescData
}

var file_msgItem_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msgItem_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_msgItem_proto_goTypes = []interface{}{
	(TIP_TYPE)(0),          // 0: message.TIP_TYPE
	(*NotifyItems)(nil),    // 1: message.NotifyItems
	(*UseItemReq)(nil),     // 2: message.UseItemReq
	(*UseItemRes)(nil),     // 3: message.UseItemRes
	(*UseExtParams)(nil),   // 4: message.UseExtParams
	(*NotifyTipItems)(nil), // 5: message.NotifyTipItems
	(*SellItemReq)(nil),    // 6: message.SellItemReq
	(*SellItemRes)(nil),    // 7: message.SellItemRes
	(*Item)(nil),           // 8: message.Item
	(MSG_RESULT)(0),        // 9: message.MSG_RESULT
}
var file_msgItem_proto_depIdxs = []int32{
	8, // 0: message.NotifyItems.Items:type_name -> message.Item
	4, // 1: message.UseItemReq.Params:type_name -> message.UseExtParams
	9, // 2: message.UseItemRes.Result:type_name -> message.MSG_RESULT
	0, // 3: message.NotifyTipItems.Tip:type_name -> message.TIP_TYPE
	8, // 4: message.NotifyTipItems.Items:type_name -> message.Item
	8, // 5: message.SellItemReq.Items:type_name -> message.Item
	9, // 6: message.SellItemRes.Result:type_name -> message.MSG_RESULT
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_msgItem_proto_init() }
func file_msgItem_proto_init() {
	if File_msgItem_proto != nil {
		return
	}
	file_base_proto_init()
	file_msgtype_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msgItem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgItem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgItem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseItemRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgItem_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseExtParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgItem_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyTipItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgItem_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgItem_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SellItemRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgItem_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgItem_proto_goTypes,
		DependencyIndexes: file_msgItem_proto_depIdxs,
		EnumInfos:         file_msgItem_proto_enumTypes,
		MessageInfos:      file_msgItem_proto_msgTypes,
	}.Build()
	File_msgItem_proto = out.File
	file_msgItem_proto_rawDesc = nil
	file_msgItem_proto_goTypes = nil
	file_msgItem_proto_depIdxs = nil
}
