// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        (unknown)
// source: role.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//[Sync(Root.Role)]
//[Inject(RoleMeta)]
type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID        int64       `protobuf:"varint,1,opt,name=UID,json=uID,proto3" json:"UID"`
	RID        int64       `protobuf:"varint,2,opt,name=RID,json=rID,proto3" json:"RID"`
	SID        int64       `protobuf:"varint,3,opt,name=SID,json=sID,proto3" json:"SID"`
	Name       string      `protobuf:"bytes,4,opt,name=Name,json=name,proto3" json:"Name"`
	IconW      string      `protobuf:"bytes,5,opt,name=IconW,json=iconW,proto3" json:"IconW"`
	Level      int32       `protobuf:"varint,6,opt,name=Level,json=level,proto3" json:"Level"`
	Exp        int64       `protobuf:"varint,7,opt,name=Exp,json=exp,proto3" json:"Exp"`
	VipLevel   int32       `protobuf:"varint,8,opt,name=VipLevel,json=vipLevel,proto3" json:"VipLevel"`
	VipExp     int64       `protobuf:"varint,9,opt,name=VipExp,json=vipExp,proto3" json:"VipExp"`
	Gold       int64       `protobuf:"varint,10,opt,name=Gold,json=gold,proto3" json:"Gold"`
	Items      []*Item     `protobuf:"bytes,11,rep,name=Items,json=items,proto3" json:"Items"`
	Buildings  []*Building `protobuf:"bytes,12,rep,name=Buildings,json=buildings,proto3" json:"Buildings"`
	Islands    []*Island   `protobuf:"bytes,13,rep,name=Islands,json=islands,proto3" json:"Islands"`
	EndpointId int32       `protobuf:"varint,14,opt,name=EndpointId,json=endpointId,proto3" json:"EndpointId"`
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Role) GetRID() int64 {
	if x != nil {
		return x.RID
	}
	return 0
}

func (x *Role) GetSID() int64 {
	if x != nil {
		return x.SID
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetIconW() string {
	if x != nil {
		return x.IconW
	}
	return ""
}

func (x *Role) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Role) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Role) GetVipLevel() int32 {
	if x != nil {
		return x.VipLevel
	}
	return 0
}

func (x *Role) GetVipExp() int64 {
	if x != nil {
		return x.VipExp
	}
	return 0
}

func (x *Role) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *Role) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Role) GetBuildings() []*Building {
	if x != nil {
		return x.Buildings
	}
	return nil
}

func (x *Role) GetIslands() []*Island {
	if x != nil {
		return x.Islands
	}
	return nil
}

func (x *Role) GetEndpointId() int32 {
	if x != nil {
		return x.EndpointId
	}
	return 0
}

// 数据变化和进游戏时，同步基本数据
type NotifyRoleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//[Sync(Root.Role.UID)]
	UID int64 `protobuf:"varint,1,opt,name=UID,json=uID,proto3" json:"UID"`
	//[Sync(Root.Role.RID)]
	RID int64 `protobuf:"varint,2,opt,name=RID,json=rID,proto3" json:"RID"`
	//[Sync(Root.Role.SID)]
	SID int64 `protobuf:"varint,3,opt,name=SID,json=sID,proto3" json:"SID"`
	//[Sync(Root.Role.Name)]
	Name string `protobuf:"bytes,4,opt,name=Name,json=name,proto3" json:"Name"`
	//[Sync(Root.Role.IconW)]
	IconW string `protobuf:"bytes,5,opt,name=IconW,json=iconW,proto3" json:"IconW"`
	//[Sync(Root.Role.Level)]
	Level int32 `protobuf:"varint,6,opt,name=Level,json=level,proto3" json:"Level"`
	//[Sync(Root.Role.Exp)]
	VipLevel int32 `protobuf:"varint,7,opt,name=VipLevel,json=vipLevel,proto3" json:"VipLevel"`
	//[Sync(Root.Role.VipExp)]
	VipExp int64 `protobuf:"varint,8,opt,name=VipExp,json=vipExp,proto3" json:"VipExp"`
	//[Sync(Root.Role.Exp)]
	Exp int64 `protobuf:"varint,9,opt,name=Exp,json=exp,proto3" json:"Exp"`
	//[Sync(Root.Role.Gold)]
	Gold int64 `protobuf:"varint,10,opt,name=Gold,json=gold,proto3" json:"Gold"`
}

func (x *NotifyRoleInfo) Reset() {
	*x = NotifyRoleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyRoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRoleInfo) ProtoMessage() {}

func (x *NotifyRoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRoleInfo.ProtoReflect.Descriptor instead.
func (*NotifyRoleInfo) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyRoleInfo) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *NotifyRoleInfo) GetRID() int64 {
	if x != nil {
		return x.RID
	}
	return 0
}

func (x *NotifyRoleInfo) GetSID() int64 {
	if x != nil {
		return x.SID
	}
	return 0
}

func (x *NotifyRoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotifyRoleInfo) GetIconW() string {
	if x != nil {
		return x.IconW
	}
	return ""
}

func (x *NotifyRoleInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *NotifyRoleInfo) GetVipLevel() int32 {
	if x != nil {
		return x.VipLevel
	}
	return 0
}

func (x *NotifyRoleInfo) GetVipExp() int64 {
	if x != nil {
		return x.VipExp
	}
	return 0
}

func (x *NotifyRoleInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *NotifyRoleInfo) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

var File_role_proto protoreflect.FileDescriptor

var file_role_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0c, 0x69, 0x73, 0x6c, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xf7, 0x02, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03,
	0x53, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x63, 0x6f, 0x6e, 0x57, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x63, 0x6f, 0x6e, 0x57, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10,
	0x0a, 0x03, 0x45, 0x78, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x78, 0x70,
	0x12, 0x1a, 0x0a, 0x08, 0x56, 0x69, 0x70, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x76, 0x69, 0x70, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06,
	0x56, 0x69, 0x70, 0x45, 0x78, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x76, 0x69,
	0x70, 0x45, 0x78, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f, 0x6c, 0x64, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x12, 0x23, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x2f, 0x0a,
	0x09, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x29,
	0x0a, 0x07, 0x49, 0x73, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x73, 0x6c, 0x61, 0x6e, 0x64,
	0x52, 0x07, 0x69, 0x73, 0x6c, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x22, 0xe0, 0x01, 0x0a, 0x0e, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x49, 0x44, 0x12, 0x10,
	0x0a, 0x03, 0x52, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x72, 0x49, 0x44,
	0x12, 0x10, 0x0a, 0x03, 0x53, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x63, 0x6f, 0x6e, 0x57, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x63, 0x6f, 0x6e, 0x57, 0x12, 0x14, 0x0a, 0x05,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x56, 0x69, 0x70, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x76, 0x69, 0x70, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x56, 0x69, 0x70, 0x45, 0x78, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x76, 0x69, 0x70, 0x45, 0x78, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x78, 0x70, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x47, 0x6f, 0x6c, 0x64,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x42, 0x0a, 0x5a, 0x08,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_role_proto_rawDescOnce sync.Once
	file_role_proto_rawDescData = file_role_proto_rawDesc
)

func file_role_proto_rawDescGZIP() []byte {
	file_role_proto_rawDescOnce.Do(func() {
		file_role_proto_rawDescData = protoimpl.X.CompressGZIP(file_role_proto_rawDescData)
	})
	return file_role_proto_rawDescData
}

var file_role_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_role_proto_goTypes = []interface{}{
	(*Role)(nil),           // 0: message.Role
	(*NotifyRoleInfo)(nil), // 1: message.NotifyRoleInfo
	(*Item)(nil),           // 2: message.Item
	(*Building)(nil),       // 3: message.Building
	(*Island)(nil),         // 4: message.Island
}
var file_role_proto_depIdxs = []int32{
	2, // 0: message.Role.Items:type_name -> message.Item
	3, // 1: message.Role.Buildings:type_name -> message.Building
	4, // 2: message.Role.Islands:type_name -> message.Island
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_role_proto_init() }
func file_role_proto_init() {
	if File_role_proto != nil {
		return
	}
	file_base_proto_init()
	file_island_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_role_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyRoleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_role_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_proto_goTypes,
		DependencyIndexes: file_role_proto_depIdxs,
		MessageInfos:      file_role_proto_msgTypes,
	}.Build()
	File_role_proto = out.File
	file_role_proto_rawDesc = nil
	file_role_proto_goTypes = nil
	file_role_proto_depIdxs = nil
}
